#! /bin/sh

### AUTOSTART ###
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
sxhkd &
picom &
redshift &
flameshot &
nm-applet &
xsetroot -cursor_name left_ptr
xrdb -merge $HOME/.Xresources

#polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#fix Java Apps grey screen
wmname LG3D &

### restore Background desktop ####
$HOME/.fehbg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focused_border_color \#4c566a
bspc config normal_border_color \#2e3440
bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a TelegramDesktop state=floating
#bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
